apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manualApproval

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  
permissions:
  scm-token-own: read
  id-token: none
  scm-token-org: read
  contents: read
      
jobs:
  test:
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1
      with:
        fetch-depth: "5"
    - id: showLastChanges
      name: Show last git changes
      uses: docker://python:3.11
      run: |
        changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)
        changed_dirs=$(echo "$changed_files" | xargs -n1 dirname | sort | uniq)
        echo "=== Changed dirs ==="
        echo "$changed_dirs"
    - id: createManualApprove
      name: Create Manual Approve
      uses: docker://alpine/curl:latest
      run: |  
        curl -i -X 'POST' "$URL/v1/workflows/approval" -d '{"approvers": ["0a808e26-f884-11ec-aa0a-42010a83ae55"], "instruction": "Please approve kushal req", "disallowLaunchByUser": false}' -H "Authorization: Bearer $JWT" -H 'Content-Type: application/json'
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.id }}
        JWT: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
    - id: respondManualApprove
      name: Respond to Manual Approval
      uses: docker://alpine/curl:latest
      run: |  
        curl -i -X 'POST' "$URL/v1/workflows/8f66482b-2e53-47b2-950e-7894771a2eaf/runs/$RUN_ID/attempts/1/jobs/$JOB_ID/approval" -d '{ "approved": true,"comments": "Passed"}' -H "Authorization: Bearer $JWT" -H 'Content-Type: application/json'
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.id }}
        JWT: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}    
